name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build
      - run: mv dist org-roam-ui-lite
      - run: zip -r ./org-roam-ui-lite.zip org-roam-ui-lite

      - name: Create release & upload asset
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: org-roam-ui-lite.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}